name: Render Quarto README

on:
  push:
    paths:
      - README.qmd

jobs:
  render-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set Up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies With Poetry
        run: poetry install --with dev

      - name: Set QUARTO_PYTHON to Poetry Environment
        run: echo "QUARTO_PYTHON=$(poetry env info --path)/bin/python" >> "$GITHUB_ENV"

      - name: Render README.md From README.qmd
        run: quarto render README.qmd

      - name: Commit And Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md README.qmd || echo "Nothing to commit"
          git commit -m "Render README.qmd To README.md" || echo "No changes to commit"
          git push || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
