on:
  push:
    branches: [main, master]
  pull_request:

name: deptry-check.yaml

permissions: read-all

jobs:
  check:
    name: deptry-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install & Run Deptry
        run: |
          uvx deptry forecasttools tests
