name: Workflow For Tests In Forecasttools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - name: cache poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry

      - name: install poetry
        run: pip install poetry

      - name: install package
        run: poetry install --with test

      - name: run tests
        run: |
          poetry run pytest
